export enum UserRole {
  SYSTEM_SUPER_ADMIN = "SYSTEM_SUPER_ADMIN",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  PATROL = "PATROL",
  CITIZEN = "CITIZEN",
}

export enum OTPType {
  FORGOT_PASSWORD_OTP = "FORGOT-PASSWORD-OTP",
  REGISTRATION_OTP = "REGISTRATION-OTP",
  FORGOT_PIN_OTP = "FORGOT-PIN-OTP",
}

export enum PINType {
  SETUP = "SETUP",
  RESET = "RESET",
}

export enum UserStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
}

export enum OTPStatus {
  REQUESTED = "REQUESTED",
  EXPIRED = "EXPIRED",
  USED = "USED",
}

export enum TokenType {
  ACCESS = "ACCESS",
  REFRESH = "REFRESH",
  PASSWORD_RESET = "PASSWORD_RESET",
  REGISTRATION = "REGISTRATION",
  SET_PASSWORD = "SET_PASSWORD",
  PIN_RESET = "PIN_RESET",
}

export enum ReportStatus {
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
  REJECTED = "REJECTED",
  ESCALATED = "ESCALATED",
}

export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  AUDIO = "AUDIO",
}

export enum ReportTypeEnum {
  NOISE = "NOISE",
  LITTERING = "LITTERING",
  VANDALISM = "VANDALISM",
  AIR_POLLUTION = "AIR_POLLUTION",
  WATER_POLLUTION = "WATER_POLLUTION",
  SOIL_CONTAMINATION = "SOIL_CONTAMINATION",
  ILLEGAL_DUMPING = "ILLEGAL_DUMPING",
  DEFORESTATION = "DEFORESTATION",
  HAZARDOUS_WASTE = "HAZARDOUS_WASTE",
  WILDLIFE_POACHING = "WILDLIFE_POACHING",
  OTHERS = "OTHERS",
}

export enum EvidenceType {
  PHOTO = "PHOTO",
  VIDEO = "VIDEO",
  BOTH = "BOTH",
}

export enum NotificationType {
  REPORT_SUBMITTED = "REPORT_SUBMITTED",
  REPORT_ASSIGNED = "REPORT_ASSIGNED",
  REPORT_STATUS_UPDATED = "REPORT_STATUS_UPDATED",
  PATROL_FOLLOW_UP = "PATROL_FOLLOW_UP",
  GENERAL = "GENERAL",
}

export enum NoiseAreaType {
  RESIDENTIAL = "RESIDENTIAL",
  COMMERCIAL = "COMMERCIAL",
}
